base_url = "https://inkagu.co"
title = "inkaguco"
description = "Gusto's personal website"

default_language = "en"

taxonomies = [
    { name = "tags", feed = true},
    { name = "meta", feed = true},
    { name = "threads", feed = true},
]

[markdown]
external_links_target_blank = true

[markdown.highlighting]
light_theme = "rose-pine-dawn"
dark_theme = "rose-pine-moon"

[extra]
