name = "inkagu"
description = "A theme developed for personal use"
license = "MIT"
homepage = "https://github.com/bacv/inkagu-co"
min_version = "0.11.0"
demo = "https://inkagu.co/"

[author]
name = "Gusto"
homepage = "https://inkagu.co"
